# Generated by Django 5.1 on 2024-10-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jruapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewEngagementsByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('engagement_count', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'view_engagements_by_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewFeedbackByRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('rating_count', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'view_feedback_by_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewProductEngagementOverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('engagement_count', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
            options={
                'db_table': 'view_product_engagement_over_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSupportInquiriesByStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status_count', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'view_support_inquiries_by_status',
                'managed': False,
            },
        ),
    ]
