# Generated by Django 5.1 on 2024-11-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jruapp', '0002_viewengagementsbytype_viewfeedbackbyrating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('liker_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProductFeedbackView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('stud_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], max_length=7)),
                ('verified', models.BooleanField(default=False)),
                ('profile_url', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user_date_created', models.DateTimeField()),
                ('product_id', models.IntegerField()),
                ('title', models.CharField(max_length=455)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_posted', models.DateTimeField()),
                ('feedback_id', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('feedback_date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_product_feedback_view',
                'managed': False,
            },
        ),
    ]
